version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - chelt-chat-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '80:80'
    networks:
      - chelt-chat-network

networks:
  chelt-chat-network:
    driver: bridge 