name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx nx run frontend:build
      - run: npx nx run frontend-e2e:e2e
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - run: go test ./backend/tests/...
