name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx nx run frontend:build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - run: npx nx run frontend-e2e:e2e
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Start backend server
        run: cd backend && go run main.go &
      - name: Wait for backend to be ready
        run: |
          timeout 30 bash -c 'while ! curl -s http://localhost:8080; do sleep 1; done'
      - name: Run backend tests
        run: cd backend && go test ./tests/... -count=1
